### ISSUE TITLE
Insets are not applied on orientation change (screen rotation)

### ISSUE THREAD

**Issue by janbolat** [chrisbanes/insetter#107]
Hello,
Insets are not applied when the device's screen is rotated and new activity is created.
What can be the cause?
My activity is fullscreen.
Using v0.5

**Comment by chrisbanes** [comment]
What are you using? What’s the code look like? Quite obviously there’s not enough information here.

**Comment by janbolat** [comment]
Seems to be a bug in the core-ktx library: https://issuetracker.google.com/issues/182063672 :(

Waiting for a stable version: https://issuetracker.google.com/issues/183955852 🤞

**Comment by chrisbanes** [comment]
Thanks for letting me know. Closing this then as it's an AndroidX bug.
