### ISSUE TITLE
0.5.0 is not available at jitpack.io anymore

### ISSUE THREAD

**Issue by thebino** [chrisbanes/insetter#117]
Builds using the version `0.5.0` are broken since today.

Looks like something has broken the jitpack.io package structure.

See the error message at [jitpack.io](https://jitpack.io/dev/chrisbanes/insetter/insetter/0.5.0/insetter-0.5.0.pom)
> Build failed. See the log at jitpack.io

**Comment by chrisbanes** [comment]
The Jitpack builds are not supported at all.

**Comment by thebino** [comment]
Looks like it wasn't available on any other repository on that time.
```
mavenLocal()
google()
jcenter()
maven("https://maven.google.com")
maven("https://packagecloud.io/optile/android/maven2")
maven ("https://jitpack.io")
```
