### ISSUE TITLE
Issue with animated inset keyboard padding

### ISSUE THREAD

**Issue by kriticalflare** [chrisbanes/insetter#119]
I am facing a few issues with using the animated ime support in my app.  As you can see the edittext's animate upwards and drop back again behind the keyboard 

Went through a few issues and i think the issue is similar to https://github.com/chrisbanes/insetter/issues/93. Hence, i tried applying the padding to the linearlayout as recommended there but the issue persists as shown in the attached video.

I have attached my project along with relevant commit https://github.com/kriticalflare/SocietyApp/tree/84088adbab5e7dae533ae5dc443aaa2c3c0c38be

https://user-images.githubusercontent.com/42350771/133146079-cd3ca98a-8451-4b2f-a82f-423bc5c30e79.mp4

**Comment by ViktoriiaPalykhata** [comment]
@kriticalflare 
Do you use fitsSystemWindows="true"?
I had this issue when use this in the root view

**Comment by rusmichal** [comment]
I had the same issue `fitsSystemWindows="true"` helped me but should we really use `fitsSystemWindows` according to this [video](https://www.youtube.com/watch?v=_mGDMVRO3iE&t=889s). This confusing a lot. Why we need to even thinking about moving we below the status bar....
