### ISSUE TITLE
Add way to consume inset dimensions 

### ISSUE THREAD

**Issue by chrisbanes** [chrisbanes/insetter#23]
See FR 2 & 3 in #16

**Comment by AlexeyKorshun** [comment]
It would be great to add an ability to return a custom insets.

**Comment by chrisbanes** [comment]
@AlexeyKorshun Do you have a use case in mind?

**Comment by AlexeyKorshun** [comment]
@chrisbanes yes, if i don't use ConstraintLayout.
Also I can return override bottom inset from FAB for recycler view, in which I use it for set bottom padding, instead of calculating padding in recycler.
