### ISSUE TITLE
Request: also add support for margins

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [chrisbanes/insetter#24]
Not just padding.

**Comment by chrisbanes** [comment]
Margins are already supported. See https://github.com/chrisbanes/insetter/tree/master/dbx

**Comment by AndroidDeveloperLB** [comment]
So you have something like:
```
    inline fun View.updateMargins(@Px left: Int = marginLeft, @Px top: Int = marginTop, @Px right: Int = marginRight, @Px bottom: Int = marginBottom) {
        updateLayoutParams<ViewGroup.MarginLayoutParams> {
            this.bottomMargin = bottom
            this.topMargin = top
            this.leftMargin = left
            this.rightMargin = right
        }
    }
```
?

**Comment by chrisbanes** [comment]
No, but that is out of the scope of this library. The `core-ktx` equivalent would be `View.updateLayoutParams()`

**Comment by AndroidDeveloperLB** [comment]
@chrisbanes Why is it out of scope?
You use it for:
```
bottomNav.doOnApplyWindowInsets { view, insets, initialPadding, initialMargins ->
    // padding contains the original padding values after inflation
    view.updatePadding(
        bottom = initialPadding.bottom + insets.systemWindowInsetBottom
    )
}
```
Also, as I've written, I use `updateLayoutParams` already. It's different than using MarginLayoutParams. It doesn't offer the various values like setting the padding.

**Comment by AndroidDeveloperLB** [comment]
Anyway, requested here:
https://issuetracker.google.com/issues/142999995

**Comment by chrisbanes** [comment]
`updatePadding()` is from core-ktx and is used as an example. This library is solely for handling insets, and `updateMargins()` isn't specific to insets.

**Comment by AndroidDeveloperLB** [comment]
Sorry for that. Say, can you please show a sample of using it with RecyclerView ? For some reason, even without using this library, I got into issues:

https://stackoverflow.com/questions/58617055/how-to-support-full-screen-navigation-ui-for-recyclerview

Since this is quite a new topic and I don't see much being talked about this, I guess this is a bug, so I reported about this here:
https://issuetracker.google.com/issues/143530492
