### ISSUE TITLE
Does this library work on KitKat and below?

### ISSUE THREAD

**Issue by truistic** [chrisbanes/insetter#32]
Hello, I see that [`setOnApplyWindowInsetsListener()`](https://developer.android.com/reference/android/view/View.html#setOnApplyWindowInsetsListener(android.view.View.OnApplyWindowInsetsListener)) method was added in API level 20, so does this library work on KitKat and below?

**Comment by chrisbanes** [comment]
Depends what you mean by work. Inset handling on KitKat and below is rarely needed, so it gracefully ignores.

What do you need to happen on KitKat and below?

**Comment by truistic** [comment]
Thank you for your reply.

My English is not very good, and I may not express it well.

The "work" I mean is when I enable drawing behind the navigation bar with `View.SYSTEM_UI_FLAG_LAYOUT_STABLE` and `View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION` flags, and use `Insetter.setOnApplyInsetsListener()` method to add padding to views, whether their content will not be displayed behind the navigation bar on KitKat and below.

My project's `minSDKVersion` is 19 now, I am also wondering if I need to upgrade it to 21.

**Comment by chrisbanes** [comment]
On KitKat, the only way to draw behind the status this to work is by using the `android:windowTranslucentNavigation` and `android:windowTranslucentStatus` attributes in your theme. Generally apps should avoid these, just use `android:statusBarColor`, etc available in API 21.

At the same time, Insetter relies on `WindowInsetsCompat`, which only works on API 21+. The effort to support KitKat is too much to make it worth it.

So summary, you can safely use keep your `minSdkVersion` as 19, but only draw behind the status bar on API 21+.

**Comment by truistic** [comment]
Ok, thank you!
