### ISSUE TITLE
Request: please explain more about the attribute "app:layout_edgeToEdge"

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [chrisbanes/insetter#38]
This is the only thing I can see about it:
https://github.com/chrisbanes/insetter/blob/master/dbx/README.md#edge-to-edge-attributes

"
There is currently just one edge-to-edge attribute:

app:layout_edgeToEdge: Set this view's system-ui visibility with the flags required to be laid out 'edge-to-edge', or not.
"

But what does it do? When to use it? When is it useful? 
Is it for Edge display? How is it related to insets?

Please explain.

**Comment by NickM-27** [comment]
It makes it so that the view is drawn behind the system bars IE there is no opaque system bars. You are now responsible for handling your views not being obstructed by those bars (which is the point of the rest of the binding attributes, so that you can avoid views being obstructed.

**Comment by AndroidDeveloperLB** [comment]
So it's not something new, right? Can you show how to use it? I don't see it being used in the sample...
