### ISSUE TITLE
Using android:windowTranslucentStatus causes problem with adjustResize

### ISSUE THREAD

**Issue by KaeMs** [chrisbanes/insetter#39]
I am using this library for a form which uses fullscreen mode for drawing the form behind `statusBar`. I am very delighted to have found this amazing library which helps in calculating the insets rather than calculating it manually, for that, I thank you.

As for the issue, forms would normally has `EditText`s and mine have several. 
I was only using `app:paddingTopSystemWindowInsets="@{true}"` for the layout as I only need the top padding. But this causes problem as my Activity doesn't respect `adjustResize` anymore, unelss I add `app:paddingBottomSystemWindowInsets="@{true}"`.

Is this an intended behavior?
Or is it actually an issue?

**Comment by chrisbanes** [comment]
Yeah, this is working as intended by the Android system.

**Comment by KaeMs** [comment]
Can you please explain why? Im curious as I thought insets are only for the on screen statusbar and the triangle circle square navigation

**Comment by chrisbanes** [comment]
This isn't really the forum for explaining platform behavior. Feel free to ask this on StackOverflow and I'll try and answer there.

**Comment by KaeMs** [comment]
Sure, here's the [link](https://stackoverflow.com/questions/59297129/using-androidwindowtranslucentstatus-causes-problem-with-adjustresize-while-usi) to the question in StackOverflow
