### ISSUE TITLE
Not compatible with CollapsingToolbarLayout

### ISSUE THREAD

**Issue by percula** [chrisbanes/insetter#41]
When using this library with a `CollapsingToolbarLayout`, the insets on the bottom (the top works) are not set or are overwritten. When I comment out the `CollapsingToolbarLayout`, the problem goes away. Please see the sample project I created: https://github.com/percula/CollapsingToolbarInsets

In the following screenshot, the FAB and the padding of the text should be above the nav bar.
![Screenshot_1576528495](https://user-images.githubusercontent.com/16809252/70941061-a4d64b00-2019-11ea-8351-42354f657002.png)

**Comment by chrisbanes** [comment]
Yeah, this will happen with `CoordinatorLayout`. It is very opinionated about inset handling (which is one of the reasons why I wrote Insetter), which makes custom inset handling hard.

You can turn all of that off by setting `android:fitsSystemWindows=“false”` on the CoordinatorLayout. Then Insetter should work like on any other view.

**Comment by percula** [comment]
Thanks, but unfortunately that doesn't fix it. I set `android:fitsSystemWindows="false"` and nothing changed 😟. I updated my sample with this.

My theory is that the `OnoffsetChangedListener` that the `CollapsingToolbarLayout` adds is overwriting the work that Insetter is doing. I'm looking through the source now to find out why/how.

**Comment by percula** [comment]
Ok, I found a solution.

Turns out the `CollapsingToolbarLayout` is preventing the `OnApplyWindowInsetsListener` for Views outside the `AppBarLayout` from ever being notified. Listeners within the `AppBarLayout` were being notified as expected. This looks like a bug within `CollapsingToolbarLayout`, probably in `CollapsingToolbarLayout.onWindowInsetChanged()` line 295 where it consumes all the window insets instead of returning them. 

As a work-around, I modified your `applySystemWindows` method to apply the listener to the `rootView`:

```kotlin
fun applySystemWindowsWithCollapsingToolbar(
        view: View,
        applyLeft: Boolean,
        applyTop: Boolean,
        applyRight: Boolean,
        applyBottom: Boolean
) {
    view.rootView.doOnApplyWindowInsets { _, insets, padding ->
        val left = if (applyLeft) insets.systemWindowInsetLeft else 0
        val top = if (applyTop) insets.systemWindowInsetTop else 0
        val right = if (applyRight) insets.systemWindowInsetRight else 0
        val bottom = if (applyBottom) insets.systemWindowInsetBottom else 0

        view.setPadding(
                padding.paddings.left + left,
                padding.paddings.top + top,
                padding.paddings.right + right,
                padding.paddings.bottom + bottom
        )
    }
}
```

However, this breaks the listeners within the `AppBarLayout`. So for now, I have two sets of binding adapters, one from Insetter and a custom set (above) just for this edge case.
