### ISSUE TITLE
Duplicate class dev.chrisbanes.insetter.DataBinderMapperImpl

### ISSUE THREAD

**Issue by bogdanzurac** [chrisbanes/insetter#46]
This library doesn't appear to be working.

After just adding the library to the project:

`implementation "dev.chrisbanes:insetter-dbx:0.2.0"`

And then syncing Gradle files + rebuilding the project, we get the following errors:

```
Duplicate class dev.chrisbanes.insetter.DataBinderMapperImpl found in modules jetified-insetter-dbx-0.2.0-runtime.jar (dev.chrisbanes.insetter:insetter-dbx:0.2.0) and jetified-insetter-dbx-0.2.0-runtime.jar (dev.chrisbanes:insetter-dbx:0.2.0)
Duplicate class dev.chrisbanes.insetter.DataBinderMapperImpl$InnerBrLookup found in modules jetified-insetter-dbx-0.2.0-runtime.jar (dev.chrisbanes.insetter:insetter-dbx:0.2.0) and jetified-insetter-dbx-0.2.0-runtime.jar (dev.chrisbanes:insetter-dbx:0.2.0)
Duplicate class dev.chrisbanes.insetter.DataBinderMapperImpl$InnerLayoutIdLookup found in modules jetified-insetter-dbx-0.2.0-runtime.jar (dev.chrisbanes.insetter:insetter-dbx:0.2.0) and jetified-insetter-dbx-0.2.0-runtime.jar (dev.chrisbanes:insetter-dbx:0.2.0)
Duplicate class dev.chrisbanes.insetter.InsetterBindingAdapters found in modules jetified-insetter-dbx-0.2.0-runtime.jar (dev.chrisbanes.insetter:insetter-dbx:0.2.0) and jetified-insetter-dbx-0.2.0-runtime.jar (dev.chrisbanes:insetter-dbx:0.2.0)
Duplicate class dev.chrisbanes.insetter.InsetterBindingAdapters$1 found in modules jetified-insetter-dbx-0.2.0-runtime.jar (dev.chrisbanes.insetter:insetter-dbx:0.2.0) and jetified-insetter-dbx-0.2.0-runtime.jar (dev.chrisbanes:insetter-dbx:0.2.0)
```

The external libraries being fetched are the following:

```
Gradle: dev.chrisbanes.insetter:insetter:0.2.0@aar
Gradle: dev.chrisbanes.insetter:insetter-dbx:0.2.0@aar
Gradle: dev.chrisbanes.insetter:insetter-ktx:0.2.0@aar
Gradle: dev.chrisbanes.insetter:insetter-widgets:0.2.0@aar
Gradle: dev.chrisbanes:insetter:0.2.0@jar
Gradle: dev.chrisbanes:insetter-dbx:0.2.0@aar
```

**Comment by chrisbanes** [comment]
Thanks for the report. Which version of the Android Gradle Plugin are you using?

**Comment by bogdanzurac** [comment]
3.6-rc03

**Comment by chrisbanes** [comment]
Would you mind trying the latest SNAPSHOT?

```groovy
repositories {
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
}

dependencies {
    implementation "dev.chrisbanes:insetter-XXXX:0.2.1-SNAPSHOT"
}
```

**Comment by bogdanzurac** [comment]
Yep, now it works. Cheers!

**Comment by cosminstefanxp** [comment]
Hey. I'm still getting this issue in `0.2.1`. Both dependencies get pulled in:
```
![image](https://user-images.githubusercontent.com/1536594/75860526-a4717300-5e04-11ea-8b93-dc2dc0b65b08.png)
```

And I get the duplicate class errors as above.

**Comment by cosminstefanxp** [comment]
Works fine in `0.2.1-SNAPSHOT` though:

![image](https://user-images.githubusercontent.com/1536594/75861273-d505dc80-5e05-11ea-8814-b8ac1b15e1cb.png)

**Comment by bogdanzurac** [comment]
Like @cosminstefanxp said above, this is still an issue in the final [v0.2.1](https://github.com/chrisbanes/insetter/releases/tag/v0.2.1) release. Maybe the branch was not fully merged in at the time of the release?

**Comment by cosminstefanxp** [comment]
@chrisbanes , are there any more news on this?

**Comment by chrisbanes** [comment]
I don't really understand where the `dev.chrisbanes.insetter:insetter*` artifacts are coming from. They're not on Maven Central, and not built by the library:
https://search.maven.org/search?q=g:dev.chrisbanes

**Comment by chrisbanes** [comment]
JCenter is the same 🤔 https://bintray.com/search?query=dev.chrisbanes.insetter

**Comment by cosminstefanxp** [comment]
Running `gradle app:dependencies` shows this dependency tree:
```
|    +--- dev.chrisbanes:insetter-dbx:0.2.1
|    |    +--- dev.chrisbanes:insetter:0.2.1
|    |    |    +--- dev.chrisbanes.insetter:insetter:0.2.1
|    |    |    |    \--- androidx.core:core:1.2.0-beta01 -> 1.2.0 (*)
|    |    |    +--- dev.chrisbanes.insetter:insetter-dbx:0.2.1
|    |    |    |    +--- dev.chrisbanes.insetter:insetter:0.2.1 (*)
|    |    |    |    +--- androidx.databinding:databinding-common:3.4.0 -> 4.0.0-beta03
|    |    |    |    +--- androidx.databinding:databinding-runtime:3.4.0 -> 4.0.0-beta03 (*)
|    |    |    |    \--- androidx.databinding:databinding-adapters:3.4.0 -> 4.0.0-beta03 (*)
|    |    |    +--- dev.chrisbanes.insetter:insetter-ktx:0.2.1
|    |    |    |    +--- dev.chrisbanes.insetter:insetter:0.2.1 (*)
|    |    |    |    +--- androidx.core:core:1.2.0-beta01 -> 1.2.0 (*)
|    |    |    |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.10 -> 1.3.70 (*)
|    |    |    \--- dev.chrisbanes.insetter:insetter-widgets:0.2.1
|    |    |         +--- dev.chrisbanes.insetter:insetter:0.2.1 (*)
|    |    |         \--- androidx.constraintlayout:constraintlayout:1.1.3 -> 2.0.0-beta4
|    |    |              +--- androidx.appcompat:appcompat:1.1.0 (*)
|    |    |              +--- androidx.core:core:1.1.0 -> 1.2.0 (*)
|    |    |              \--- androidx.constraintlayout:constraintlayout-solver:2.0.0-beta4
```

**Comment by chrisbanes** [comment]
This is really weird, I'm wondering if there's some weird caching going on somewhere. This is what I see in [tivi.app](https://tivi.app):

```
|    +--- dev.chrisbanes:insetter-dbx:0.2.1
|    |    +--- dev.chrisbanes:insetter:0.2.1
|    |    |    \--- androidx.core:core:1.2.0-beta01 -> 1.2.0 (*)
|    |    +--- androidx.databinding:databinding-common:3.4.0 -> 4.1.0-alpha05
|    |    +--- androidx.databinding:databinding-runtime:3.4.0 -> 4.1.0-alpha05 (*)
|    |    \--- androidx.databinding:databinding-adapters:3.4.0 -> 4.1.0-alpha05 (*)
```

Which looks totally correct. I'm going to release v0.2.2 later today so hopefully a new version fixes it.

**Comment by bogdanzurac** [comment]
Update: `v0.2.2` doesn't work. `v0.2.3-SNAPSHOT` however does.

**Comment by cosminstefanxp** [comment]
@chrisbanes , In our case, could it be due to some other repository? 

E.g., we're also using:
```
 maven { url "https://www.jitpack.io"  }
```

**Comment by chrisbanes** [comment]
There is no difference between `v0.2.2` and `v0.2.3-SNAPSHOT` other than one goes to the Sonatype staging repository, and the other goes to snapshot repo. Also, `dev.chrisbanes.insetter:insetter-XXXX` does not exist anywhere that I can find.

@cosminstefanxp Ah, that's probably the issue. You can safely remove that and use the official dependencies in the [README](https://github.com/chrisbanes/insetter#download). Check that `mavenCentral()` is above the jitpack repo in your `repositories` list.

**Comment by cosminstefanxp** [comment]
Apparently this was the issue. We had `google()`, then `jitpack`, then `jcenter()`. Placing `mavenCenter()` just below `google()` fixes it. Thank you! 

However, doesn't this mean that in either `google()`, `jitpack` or `jcenter` there's something off with regards to `insetter`?

**Comment by chrisbanes** [comment]
My guess would be Jitpack, but I have no control over it AFAICT. It builds the artifacts on demand, when someone requests the artifacts. 

You could restrict what artifacts you request from Jitpack using using [repository filters](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:repository-content-filtering):

```
repositories {
    maven {
         url "https://jitpack.io"
         content {
             includeGroup "com.library.iknowcomesfromjitpack"
         }
    }
}
```
