### ISSUE TITLE
Request: Add a BottomSheetDialog example with a RecyclerView inside

### ISSUE THREAD

**Issue by LouisCAD** [chrisbanes/insetter#66]
Hi,
I'd be nice to have an example featuring a `BottomSheetDialog`, which would have views at the top of the layout, a RecyclerView with more items than can fit in the screen, and views in the bottom as well.

This would be very helpful to not just me as I failed to find how to do it right on the public web (and failed to do it right on my own, having views behind the SystemUI).

**Comment by TemMax** [comment]
@LouisCAD could you show picture of desired BottomSheet?

**Comment by LouisCAD** [comment]
@TemMax I'm feeling a little lazy for this.
You can imagine a bottom sheet (white panel overlapping the rest of the app, anchored to the bottom of the screen, as seen in Material Design components) that is also drawn below the navigation bar for the sheet (while the content is still shown above the navigation with the desired margin).

**Comment by paulkugaev** [comment]
Looking forward to seeing such example!

**Comment by TemMax** [comment]
@LouisCAD if my imagine is right, then you may just add bottom padding to your RecyclerView?

**Comment by alexvanyo** [comment]
It doesn't use [insetter](https://github.com/chrisbanes/insetter), but I published an article detailing how to adjust the `BottomSheetDialogFragment` to go edge-to-edge [here](https://medium.com/livefront/advanced-android-edge-to-edge-part-2-bottomsheetdialogfragment-f6d7b62aeb1c) with accompanying repo [here](https://github.com/alexvanyo/android-edge2edge) (sorry for self-promoting, I hope it is useful!).

The main branch of `material-components` also has some upcoming support for insets for `BottomSheetBehavior` (and by extension `BottomSheetDialogFragment`) so you can explore using a snapshot version (for now) if that meets your requirements:

https://github.com/material-components/material-components-android/blob/master/docs/components/BottomSheetBehavior.md#handling-insets

https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/bottomsheet/BottomSheetDialog.java#L168-L184

**Comment by chrisbanes** [comment]
Thanks @alexvanyo, nice post!

I really think this is a bug in `BottomSheetDialogFragment`. Definitely worth raising a bug on the [MDC repo](https://github.com/material-components/material-components-android/issues).

**Comment by itsandreramon** [comment]
How does this work exactly? I can't find the option to set paddingBottomSystemWindowInsets.

**Comment by itsandreramon** [comment]
Is this actually correct if I use insetter? (based on @alexvanyo's [sample](https://github.com/alexvanyo/android-edge2edge/blob/main/app/src/main/java/com/alexvanyo/edge2edge/MainBottomSheetDialogFragment.kt))

```kotlin
    ...
    override fun onCreateDialog(savedInstanceState: Bundle?): Dialog =
        object : BottomSheetDialog(requireContext(), theme) {
            override fun onAttachedToWindow() {
                super.onAttachedToWindow()

                window?.let {
                    WindowCompat.setDecorFitsSystemWindows(it, false)
                }

                findViewById<View>(com.google.android.material.R.id.container)?.apply {
                    fitsSystemWindows = false
                    view?.applyInsetter {
                        type(navigationBars = true) {
                            padding()
                        }
                    }
                }

                findViewById<View>(com.google.android.material.R.id.coordinator)?.fitsSystemWindows = false
            }
}
```

**Comment by itsandreramon** [comment]
Is this actually correct if I use Insetter? (based on @alexvanyo's [sample)](https://github.com/alexvanyo/android-edge2edge/blob/main/app/src/main/java/com/alexvanyo/edge2edge/MainBottomSheetDialogFragment.kt)

```kotlin
open class MyBottomSheetDialogFragment : BottomSheetDialogFragment() {

    override fun onCreateDialog(savedInstanceState: Bundle?): Dialog =
        object : BottomSheetDialog(requireContext(), theme) {
            override fun onAttachedToWindow() {
                super.onAttachedToWindow()

                window?.let {
                    WindowCompat.setDecorFitsSystemWindows(it, false)
                }

                findViewById<View>(com.google.android.material.R.id.container)?.apply {
                    fitsSystemWindows = false

                    view?.applyInsetter {
                        type(navigationBars = true) {
                            padding()
                        }
                    }
                }

                findViewById<View>(com.google.android.material.R.id.coordinator)?.fitsSystemWindows = false
            }
        }
    }
}
```

**Comment by alexvanyo** [comment]
@itsandreramon It depends on the behavior you are going for!

One comment for the above code is that `view?.applyInsetter` is acting on the `Fragment.getView()`, and not the `com.google.android.material.R.id.container`, even though the nesting seems to imply otherwise. You'd probably be better off applying those insets directly in `onViewCreated`, rather than in the `onAttachedToWindow` callback.

If the content in your bottom sheet can be really big (large enough to fill up the entire screen), you might also see your content interact strangely with the status bar unless you also apply the status bar insets.

The latest `1.4.0-alpha` versions of the material components library also now have more built-in support for going edge-to-edge, including some fancy dynamic updating of the status bar color.

**Comment by itsandreramon** [comment]
Thank you very much, will fix this :)

**Comment by itsandreramon** [comment]
@alexvanyo @chrisbanes @nickbutcher is there a sample on how to use the new built in insets apis? the material docs only state the following, which I cannot get to work (https://material.io/components/sheets-bottom/android#usage)
<img width="749" alt="Screenshot 2021-06-22 at 13 25 01" src="https://user-images.githubusercontent.com/17139385/122917065-e60d9080-d35d-11eb-803e-d245f36be23a.png">
