### ISSUE TITLE
Support Insets for Android R 

### ISSUE THREAD

**Issue by mercuriy94** [chrisbanes/insetter#74]
Hello
Are you planning to add support to this library of api inserts from Android 11? Or will it all be implemented in another library?

Thanks you

**Comment by NickM-27** [comment]
He told me on Twitter he is hoping to add it to this library very soon https://twitter.com/chrisbanes/status/1297172768262361088

**Comment by chrisbanes** [comment]
Yes, I'll update Insetter with the new APIs, but probably not for a few weeks (vacation first).

I also want to think about the APIs a bit more, to make them fit naturally with the new Type system.

**Comment by mercuriy94** [comment]
Thanks for the answer!
First, I wish you a good rest on vacation)
We are waiting for when you can update the library)
Thanks you)

**Comment by chrisbanes** [comment]
No problem, I'll leave this open to track.

**Comment by NickM-27** [comment]
@chrisbanes Checkin in to see how this is going?

**Comment by chrisbanes** [comment]
I'm waiting for [this](https://twitter.com/chrisbanes/status/1337417907144445959) to be released before working on this. It will have an effect on the API so want to do it once 🙂

**Comment by dimiitpk** [comment]
@chrisbanes 
Is there any date where it will be done ? :D

**Comment by chrisbanes** [comment]
Woops, forgot to update this. This
Was released in 0.5.0: https://github.com/chrisbanes/insetter/releases/tag/v0.5.0
