### ISSUE TITLE
Issues applying to margins after updating to 0.5.0

### ISSUE THREAD

**Issue by CarlosEsco** [chrisbanes/insetter#98]
Upgraded to the 0.5.0 from 0.3.1

Code was this
```
   recycler.applySystemWindowInsetsToMargin(top = true)
  recycler.applySystemGestureInsetsToPadding(bottom = true)
```
and is now this
```
recycler.applyInsetter {
                type(systemGestures = true) {
                    padding(bottom = true)
                }
                type(statusBars = true) {
                    margin(top = true)
                }
            }
```

I have to apply the statusbars to margin top or else it fails

View's LayoutParams do not extend MarginLayoutParams errors since updating
  java.lang.IllegalArgumentException: Margin window insets handling requested but View's LayoutParams do not extend MarginLayoutParams

**Comment by chrisbanes** [comment]
Sounds like the same issue as #79. Is the parent of `recycler` a `ConstraintLayout`? If so, what version are you using?

**Comment by CarlosEsco** [comment]
```
 const val constraintLayout = "androidx.constraintlayout:constraintlayout:2.0.4"
 const val coordinatorLayout = "androidx.coordinatorlayout:coordinatorlayout:1.1.0"
const val swipeRefresh = "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"
```
the fragment recycler's parent is a swiperefreshlayout inside of the coordinatorlayout 

This view is placed inside a standard FragmentContainerView when the fragment is attached

**Comment by chrisbanes** [comment]
Ah, well there's the issue: `SwipeRefreshLayout` doesn't support/use `MarginLayoutParams` so there's no way to add margin. This would happen the same with older versions of the library too.

If you need to use margin, I'd wrap the `RecyclerView` in a `FrameLayout`.
